version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: telegram_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
<<<<<<< HEAD
      - "5432:5432"
=======
      - "5432:5432"
 
>>>>>>> Build_an_Analytical_API
